// Demo page copy + simulated data. Owner: Lead (Claude).
// Wording comes from CONTENT.md "DEMO PAGE". Everything here is SIMULATED:
// Niek, every competitor and every .example website are fictional, and no AI model is ever called.
// Real model names are used for illustration only; every answer is labeled as simulated.

export const demoCopy = {
  badge: 'Simulated',
  disclaimer: 'Niek is a fictional brand created for this demo. AI answers are simulated.',
  title: 'See a Nexo audit in action',
  intro: 'Follow a simulated audit for Niek, a fictional running brand, from product data to an AI visibility report.',
  back: 'Back',
  steps: [
    { key: 'start', label: 'Start', title: 'Tell us about the brand', next: 'Next: Competitors' },
    { key: 'competitors', label: 'Competitors', title: 'Who do you compete with?', next: 'Next: Build test data' },
    { key: 'testdata', label: 'Test data', title: 'Build test data', next: 'Next: Run AI check' },
    { key: 'dashboard', label: 'Dashboard', title: 'AI visibility dashboard', next: 'Next: Book a consultation' },
    { key: 'consult', label: 'Consultation', title: 'Book your results consultation', next: 'Request consultation' },
  ],
};

// ---- Step 1: Start (form) ----
export const formDefaults = {
  company: 'Niek',
  email: 'marketing@niek.example',
  website: 'https://niek.example',
  location: 'Portland, OR',
  industry: 'Running shoes & apparel',
};

export const industries = [
  'Running shoes & apparel',
  'Consumer electronics',
  'Retail & e-commerce',
  'Food & beverage',
  'Home & garden',
  'Health & beauty',
  'Local services',
  'Other',
];

export const formCopy = {
  labels: {
    company: 'Company name',
    email: 'Work email',
    website: 'Website',
    location: 'Location',
    industry: 'Industry',
    file: 'Product data (CSV)',
  },
  sampleFile: { name: 'niek-products.csv', url: '/demo/niek-products.csv' },
  fileHelper: 'Your file stays in your browser. Nothing is uploaded.',
  replaceFile: 'Replace file',
  useSample: 'Use sample file',
  downloadSample: 'Download the sample CSV',
};

// ---- Step 2: Competitors ----
export const competitorsCopy = {
  text: "We'll check how often AI recommends these brands instead of you. Remove or add competitors.",
  nameLabel: 'Competitor name',
  websiteLabel: 'Website',
  optional: 'optional',
  add: 'Add',
  remove: 'Remove',
  suggestionsLabel: 'Suggestions',
  rules: 'At least 1, up to 8 competitors.',
  min: 1,
  max: 8,
};

// product names are simulated (used in the comparison test prompt).
export const knownCompetitors = [
  { name: 'Altus Running', website: 'altus.example', product: 'Altus Ridge WP' },
  { name: 'Kova Athletics', website: 'kova.example', product: 'Kova Drift Waterproof' },
  { name: 'Ridgeline Gear', website: 'ridgeline.example', product: 'Ridgeline Torrent' },
  { name: 'Summit Stride', website: 'summitstride.example', product: 'Summit Stride Rainpeak' },
  { name: 'Cadence Co.', website: 'cadence.example', product: 'Cadence Storm Runner' },
  { name: 'Northpace', website: 'northpace.example', product: 'Northpace Sleet Trail' },
  { name: 'Tempo Trail', website: 'tempotrail.example', product: 'Tempo Trail Splash Racer' },
  { name: 'Brisk Athletic', website: 'brisk.example', product: 'Brisk All-Weather Run' },
];
export const defaultCompetitorNames = ['Altus Running', 'Kova Athletics', 'Ridgeline Gear'];

// A competitor typed in by the viewer gets simulated details too.
export function makeCompetitor(name, website) {
  const known = knownCompetitors.find((c) => c.name.toLowerCase() === name.trim().toLowerCase());
  if (known) return { ...known, website: website || known.website };
  return { name: name.trim(), website: website.trim(), product: `${name.trim()} Waterproof Runner` };
}

// ---- Step 3: Test data (synthetic prompts + model choice) ----
// Real product names, shown for illustration only. No model is called; every answer is simulated.
export const models = [
  { id: 'chatgpt', name: 'ChatGPT', maker: 'OpenAI' },
  { id: 'gemini', name: 'Gemini', maker: 'Google' },
  { id: 'claude', name: 'Claude', maker: 'Anthropic' },
  { id: 'perplexity', name: 'Perplexity', maker: 'Perplexity AI' },
  { id: 'copilot', name: 'Copilot', maker: 'Microsoft' },
];

export const testDataCopy = {
  text: "Nexo's internal AI turns your product data and competitors into realistic shopper questions, then tests them across the top AI models.",
  builtFrom: (products, competitors) => `Built from ${products} products, their target customers and ${competitors} ${competitors === 1 ? 'competitor' : 'competitors'}`,
  generate: 'Generate test data',
  generating: 'Generating synthetic shopper questions…',
  generatedLabel: "Generated by Nexo's internal AI · Simulated",
  showing: 'Showing 10 of 100 generated prompts',
  columns: ['#', 'Test prompt', 'Type', 'Shopper persona'],
  headlineBadge: 'Headline prompt',
  modelsTitle: 'Choose the AI models to test',
  modelsText: 'Pick at least one. All five are selected by default.',
  modelsDisclaimer: 'Model names are shown for illustration. No models are called in this demo; every answer is simulated.',
  modelsError: 'Choose at least one AI model.',
  generateError: 'Generate the test data first.',
  summary: (n) => `100 prompts × ${n} ${n === 1 ? 'model' : 'models'} = ${100 * n} simulated tests`,
};

export const question = 'What are the best waterproof running shoes under $150?';

// 10 of the 100 synthetic prompts. The comparison prompt uses the viewer's first competitor.
export function buildPrompts(competitors) {
  const rival = competitors[0]?.product ?? 'Altus Ridge WP';
  return [
    { prompt: 'What are the best trail running shoes?', type: 'Category', persona: 'Trail runner, all levels' },
    { prompt: question, type: 'Category', persona: 'Trail runner who trains in rain and mud', headline: true },
    { prompt: 'Which trail running shoes grip best in mud?', type: 'Feature', persona: 'Trail runner, wet climate' },
    { prompt: 'What are the best trail running shoes for rainy weather?', type: 'Category', persona: 'Runner in the Pacific Northwest' },
    { prompt: 'Is the Niek Stormline Trail waterproof?', type: 'Fact check', persona: 'Shopper checking details' },
    { prompt: `${rival} vs Niek Stormline Trail for wet trails?`, type: 'Comparison', persona: 'Shopper comparing brands' },
    { prompt: 'Good trail running shoes for beginners under $150?', type: 'Budget', persona: 'New trail runner' },
    { prompt: 'What shoes should I wear for a muddy trail half marathon?', type: 'Scenario', persona: 'Race-day planner' },
    { prompt: 'What are the most comfortable trail running shoes for long distances?', type: 'Feature', persona: 'Ultra runner' },
    { prompt: 'Which brands make the best waterproof trail runners?', type: 'Brand', persona: 'Brand-curious shopper' },
  ];
}

export const niekProduct = { brand: 'Niek', sku: 'NK-101', product: 'Niek Stormline Trail' };

// ---- Step 5: Consultation (the end of the demo for now) ----
export const consultCopy = {
  text: 'A Nexo data analyst and consultant will walk you through these results, explain what AI gets wrong about your brand, suggest how to improve your product information, and re-run the test.',
  team: [
    { role: 'Data analyst', does: 'Explains every number in your report and what drives it.' },
    { role: 'Consultant', does: 'Recommends the fixes to make first and plans your re-test.' },
  ],
  availabilityTitle: 'When are you available?',
  availabilityText: 'Pick every time that works (Pacific Time). We will confirm one.',
  times: ['9:00 AM', '11:00 AM', '1:00 PM', '3:00 PM'],
  formatTitle: 'Meeting format',
  formats: ['Video call', 'Phone call'],
  notesLabel: 'Anything we should know?',
  optional: 'optional',
  pickError: 'Choose at least one time that works for you.',
  sentTitle: 'Request received',
  sentText: (email) => `Thanks! In a real engagement we would email ${email} to confirm a time with our data analyst and consultant.`,
  sentNote: 'Simulated: nothing was sent.',
  startOver: 'Start over',
};

// Next 5 weekdays from today, for the availability grid.
export function nextWeekdays(count = 5, from = new Date()) {
  const days = [];
  const d = new Date(from);
  while (days.length < count) {
    d.setDate(d.getDate() + 1);
    if (d.getDay() !== 0 && d.getDay() !== 6) {
      days.push({
        key: d.toISOString().slice(0, 10),
        label: d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }),
      });
    }
  }
  return days;
}
